repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: debug-statements
  - repo: local
    hooks:
      - id: translation-parity
        name: Translation key parity
        entry: python scripts/check_translations.py
        language: system
        pass_filenames: false
        stages: [commit]
      - id: pytest
        name: Pytest quick run
        entry: python -m pytest -q
        language: system
        pass_filenames: false
        stages: [commit]
        types: [python]
