name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
           pip install -r requirements_test.txt

      - name: Verify translation keys
        run: python scripts/check_translations.py

      - name: Run tests with coverage
        run: |
          pytest --cov=custom_components/vikunja --cov-report=term-missing --cov-report=xml

      - name: Upload coverage XML artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
